### ISSUE TITLE
Convert TypeScript Files to JavaScript

### ISSUE THREAD

**Issue by crookedneighbor** [Commander-Spellbook/website-v2#318]
In an effort to be more beginner friendly, we're going to convert the TypeScript files back to JavaScript, so beginner developers have less of a hurdle to contribute to the site.

### Tasks:

- [x] convert backend folder (addressed in #319)
- [ ] convert frontend folder
- [ ] convert scripts folder
- [ ] convert cypress folder
- [ ] convert any misc utilities
- [ ] remove TypeScript specific packages (ts-node, ts-jest, typescript, various configs, etc)

**Comment by crookedneighbor** [comment]
No longer going to happen. We'll be converting from Nuxt -> Next instead.
